### PR TITLE
Add unit tests

### LINKED ISSUE #1: Unit tests?
Hiya, would you be interested if I contribute some unit tests? We met at the AustinJS meetup and I want to get to know this tool better. I'm evaluating its usage for some projects.

### PR DESCRIPTION
**Pull request by johnapost**
* Updated dependencies (due to `prepare` script when installing)
* Added jest
* Added snapshot test for `gridWiz`

Decided to go with a snapshot test since the `gridWiz` function returns a CSS string. This makes it safer to do refactors without unintentionally changing functionality.

I'm unsure how you want to handle the version bump. There were no compile changes since I added one test, except perhaps due to dependency updates.

Resolves #1.

### CODE REVIEW

**Comment by seejamescode** [comment]
Thanks fo doing this John! I think adding unit tests shows how the source code needs to be broken up into smaller modules.

Do you think we should split tests between `grid.js` and `columns.js`, and add multiple test configs to cover oddities in config input (only one breakpoint, no max-width vs max-width, etc...)?

Minor things to take care of:
- [ ] Add a script in `package.json` for updating the snapshots
- [ ] `.npmignore` will need to list `coverage` just like `.gitignore`
- [ ] I think a dependency was accidentally installed in `website/` because `website/package-lock.json` has changes committed

**Comment by johnapost** [comment]
@seejamescode 
>Do you think we should split tests between grid.js and columns.js, and add multiple test configs to cover oddities in config input (only one breakpoint, no max-width vs max-width, etc...)?

Yes, I think that would be good. I would have done this now but it's tricky considering how the code is organized. This is partly due to the `compat` variable in `src/index.js`, which requires maintaining the closure for access to the `support` and `progressive` variables.

I was thinking it would make the `src/grid.js` and `src/columns.js` tests a regurgitation of the logic within `src/index.js`.

Would you prefer if remove the following line when installing to avoid updating other dependencies: `"prepare": "npm run build && cd website && npm i && cd ..",`? I can place it again afterwards.

**Comment by seejamescode** [comment]
> I would have done this now but it's tricky considering how the code is organized. This is partly due to the `compat` variable in `src/index.js`, which requires maintaining the closure for access to the support and progressive variables.

That makes sense. Feel free to either leave that part as-is or move it into another module that both `src/grid.js` and `src/columns.js` call.

> Would you prefer if remove the following line when installing to avoid updating other dependencies: `"prepare": "npm run build && cd website && npm i && cd ..",`? I can place it again afterwards.

I forgot about that part too. No, it is fine as-is for the sake of collaborators. We’ll survive with the lock changes. lol

**Comment by johnapost** [comment]
OK, I can follow up with another commit this week.

**Comment by johnapost** [comment]
@seejamescode Ready for you to look at again.

**Comment by seejamescode** [comment]
Thanks again for doing this @johnapost!

**Pull request merged**
